# This workflow will pass tests of module passed by input

name: som_ov_signed_documents
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'
jobs:
  erp-tests-module:
    uses: Som-Energia/openerp_som_addons/.github/workflows/reusable_workflow.yml@main
    with:
      module: som_ov_signed_documents
    secrets:
      ACCESS_TOKEN_GA: ${{ secrets.ACCESS_TOKEN_GA }}
      ESIOS_TOKEN: ${{ secrets.ESIOS_TOKEN }}
      SRID: ${{ secrets.SRID }}
